version: "3.8"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Companion'ın hangi containerların hangi domain istediğini görebilmesi için:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Aşağıdaki volume'lar da Nginx config, sertifikalar vb. için
      - proxy_confd:/etc/nginx/conf.d
      - proxy_vhostd:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - proxy_certs:/etc/nginx/certs
    networks:
      - wp_network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    # Burada environment kısmı kritik:
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      # istersen şu da eklenebilir:
      DEFAULT_EMAIL=admin@kohesoft.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy_certs:/etc/nginx/certs
      - proxy_vhostd:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
    networks:
      - wp_network

volumes:
  proxy_confd:
  proxy_vhostd:
  proxy_html:
  proxy_certs:

networks:
  wp_network:
    external: true
